# Generated by Django 4.1.2 on 2022-10-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('activitePref', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
            ],
        ),
    ]
