# Generated by Django 4.1.2 on 2022-11-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiChats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='couleur',
        ),
        migrations.AlterField(
            model_name='chat',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCouleur', models.ManyToManyField(to='TiChats.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='nomCouleur',
            field=models.ManyToManyField(to='TiChats.couleur'),
        ),
    ]
