# Generated by Django 4.1.2 on 2022-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiChats', '0002_remove_chat_couleur_alter_chat_age_couleur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='nomCouleur',
        ),
        migrations.AddField(
            model_name='chat',
            name='couleur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Couleur',
        ),
    ]
