# Generated by Django 4.1.2 on 2022-11-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiChats', '0003_remove_chat_nomcouleur_chat_couleur_alter_chat_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCouleur', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='couleur',
        ),
        migrations.AddField(
            model_name='chat',
            name='lacouleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TiChats.couleur'),
        ),
    ]
