# Generated by Django 4.1.2 on 2022-11-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiChats', '0004_couleur_remove_chat_couleur_chat_lacouleur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='lacouleur',
            new_name='couleur',
        ),
    ]
