# Generated by Django 4.1.2 on 2022-11-02 16:01

import TiChats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiChats', '0005_rename_lacouleur_chat_couleur'),
    ]


