# Generated by Django 4.1.2 on 2022-11-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiChats', '0006_alter_chat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='photo',
            field=models.ImageField(upload_to='TiChats/'),
        ),
    ]
