# Generated by Django 4.1.2 on 2022-11-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiChats', '0007_alter_chat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ageString',
            field=models.CharField(default='Ans', max_length=50),
        ),
        migrations.AlterField(
            model_name='chat',
            name='photo',
            field=models.ImageField(default='placeholder.jpg', upload_to='TiChats/'),
        ),
    ]
